name: spa-crud-frontend

proxy:
  node:
    - spa-crud-frontend.lndo.site:3000

services:
  node:
    type: node
    port: 3000
    build:
      - npm install
    command: npm start

tooling:
  npm:
    service: node
  npx:
    service: node
  node:
    service: node
  yarn:
    service: node